CREATE TABLE EMP_K (
 E_ID NUMBER PRIMARY KEY,
 E_NAME VARCHAR2(50),
 SALARY NUMBER,
 DEPARTMENT VARCHAR2(50)
);
INSERT INTO EMP_K VALUES (1, 'Kunal', 3500, 'HR');
INSERT INTO EMP_K VALUES (2, 'Aarti', 4200, 'IT');
INSERT INTO EMP_K VALUES (3, 'Ravi', 3000, 'SALES');
INSERT INTO EMP_K VALUES (4, 'Divya', 2800, 'HR');
INSERT INTO EMP_K VALUES (5, 'Mona', 3600, 'IT');
INSERT INTO EMP_K VALUES (6, 'Lalit', 3900, 'HR');
INSERT INTO EMP_K VALUES (7, 'Sunil', 2500, 'IT');

-- 1. WRITE AN SQL QUERY TO FETCH THE FIRST 5 RECORDS FROM A TABLE
SELECT * FROM EMP_K WHERE ROWNUM <= 5;
-- 2. WRITE AN SQL QUERY TO FETCH THREE MIN SALARIES FROM A TABLE
SELECT DISTINCT salary 
FROM emp_k e1
WHERE 3 > (
  SELECT COUNT(DISTINCT salary) 
  FROM emp_k e2
  WHERE e2.salary < e1.salary
)
ORDER BY salary;

-- 3. DISPLAY THE MAXIMUM SALARY BEING PAID TO CLERK
-- Adding DESIGNATION column and updating values
ALTER TABLE EMP_K ADD DESIGNATION VARCHAR2(50);

UPDATE EMP_K SET DESIGNATION = 'CLERK' WHERE E_NAME IN ('Kunal', 'Divya');
UPDATE EMP_K SET DESIGNATION = 'MANAGER' WHERE E_NAME IN ('Aarti', 'Lalit');
UPDATE EMP_K SET DESIGNATION = 'ENGINEER' WHERE E_NAME IN ('Mona', 'Ravi', 'Sunil');

-- Query to find maximum salary paid to CLERK
SELECT MAX(SALARY) AS MAX_CLERK_SALARY
FROM EMP_K
WHERE DESIGNATION = 'CLERK';
-- 4. DISPLAY DEPT NUMBERS AND TOTAL NUMBER OF EMPLOYEES WITHIN EACH GROUP
SELECT DEPARTMENT, COUNT(*) AS TOTAL_EMPLOYEES FROM EMP_K GROUP BY DEPARTMENT;
-- 5. DISPLAY THE DEPARTMENT NUMBERS WITH MORE THAN THREE EMPLOYEES IN EACH DEPT
SELECT DEPARTMENT FROM EMP_K GROUP BY DEPARTMENT HAVING COUNT(*) > 3;
