-- =====================================
-- SECTION K: EMPLOYEE(E_ID, E_NAME, SALARY, DEPARTMENT)
-- =====================================
CREATE TABLE EMP_K (
 E_ID NUMBER PRIMARY KEY,
 E_NAME VARCHAR2(50),
 SALARY NUMBER,
 DEPARTMENT VARCHAR2(50)
);
INSERT INTO EMP_K VALUES (1, 'Kunal', 3500, 'HR');
INSERT INTO EMP_K VALUES (2, 'Aarti', 4200, 'IT');
INSERT INTO EMP_K VALUES (3, 'Ravi', 3000, 'SALES');
INSERT INTO EMP_K VALUES (4, 'Divya', 2800, 'HR');
INSERT INTO EMP_K VALUES (5, 'Mona', 3600, 'IT');
INSERT INTO EMP_K VALUES (6, 'Lalit', 3900, 'HR');
INSERT INTO EMP_K VALUES (7, 'Sunil', 2500, 'IT');
-- 1. WRITE AN SQL QUERY TO FETCH THE FIRST 5 RECORDS FROM A TABLE
SELECT * FROM EMP_K WHERE ROWNUM <= 5;
-- 2. WRITE AN SQL QUERY TO FETCH THREE MIN SALARIES FROM A TABLE
SELECT DISTINCT SALARY FROM EMP_K ORDER BY SALARY ASC FETCH FIRST 3 ROWS ONLY;
-- 3. DISPLAY THE MAXIMUM SALARY BEING PAID TO CLERK
-- NOTE: As there is no DESIGNATION column, we assume CLERK is not included here
-- (Skip or modify schema to include DESIGNATION if needed)
-- 4. DISPLAY DEPT NUMBERS AND TOTAL NUMBER OF EMPLOYEES WITHIN EACH GROUP
SELECT DEPARTMENT, COUNT(*) AS TOTAL_EMPLOYEES FROM EMP_K GROUP BY DEPARTMENT;
-- 5. DISPLAY THE DEPARTMENT NUMBERS WITH MORE THAN THREE EMPLOYEES IN EACH DEPT
SELECT DEPARTMENT FROM EMP_K GROUP BY DEPARTMENT HAVING COUNT(*) > 3;
