-- =====================================
-- SECTION L: EMPLOYEE(E_ID, E_NAME, SALARY, DEPARTMENT)
-- =====================================
CREATE TABLE EMP_L (
 E_ID NUMBER PRIMARY KEY,
 E_NAME VARCHAR2(50),
 SALARY NUMBER,
 DEPARTMENT VARCHAR2(50),
 DESIGNATION VARCHAR2(30)
);
INSERT INTO EMP_L VALUES (1, 'Neeta', 2800, 'HR', 'CLERK');
INSERT INTO EMP_L VALUES (2, 'Manoj', 3100, 'IT', 'MANAGER');
INSERT INTO EMP_L VALUES (3, 'Rajeev', 2700, 'SALES', 'CLERK');
INSERT INTO EMP_L VALUES (4, 'Sneha', 2900, 'HR', 'CLERK');
INSERT INTO EMP_L VALUES (5, 'Preeti', 3500, 'HR', 'CLERK');
INSERT INTO EMP_L VALUES (6, 'Vikram', 4000, 'IT', 'CLERK');
INSERT INTO EMP_L VALUES (7, 'Anu', 3600, 'SALES', 'CLERK');
-- 1. WRITE AN SQL QUERY TO FETCH THE FIRST 5 RECORDS FROM A TABLE
SELECT * FROM EMP_L WHERE ROWNUM <= 5;
-- 2. WRITE AN SQL QUERY TO FETCH THREE MIN SALARIES FROM A TABLE
SELECT DISTINCT SALARY FROM EMP_L ORDER BY SALARY ASC FETCH FIRST 3 ROWS ONLY;
-- 3. DISPLAY THE MAXIMUM SALARY BEING PAID TO CLERK
SELECT MAX(SALARY) FROM EMP_L WHERE DESIGNATION = 'CLERK';
-- 4. DISPLAY DEPT NUMBERS AND TOTAL NUMBER OF EMPLOYEES WITHIN EACH GROUP
SELECT DEPARTMENT, COUNT(*) AS TOTAL_EMPLOYEES FROM EMP_L GROUP BY DEPARTMENT;
-- 5. DISPLAY THE DEPARTMENT NUMBERS WITH MORE THAN THREE EMPLOYEES IN EACH DEPT
SELECT DEPARTMENT FROM EMP_L GROUP BY DEPARTMENT HAVING COUNT(*) > 3;
