=====================================
-- SECTION A: EMP(EID, EMP_NAME, SALARY, DESIGNATION, DEPTNO)
-- =====================================
CREATE TABLE EMP (
 EID NUMBER PRIMARY KEY,
 EMP_NAME VARCHAR2(50),
 SALARY NUMBER,
 DESIGNATION VARCHAR2(30),
 DEPTNO NUMBER
);
INSERT INTO EMP VALUES (101, 'Alice', 4000, 'CLERK', 10);
INSERT INTO EMP VALUES (102, 'Bob', 2800, 'CLERK', 20);
INSERT INTO EMP VALUES (103, 'Carol', 3500, 'MANAGER', 10);
INSERT INTO EMP VALUES (104, 'David', 2900, 'CLERK', 30);
INSERT INTO EMP VALUES (105, 'Steve', 5000, 'CLERK', 10);
-- Answer 1:
SELECT EMP_NAME FROM EMP WHERE DEPTNO = 10;
-- Answer 2:
SELECT EMP_NAME FROM EMP WHERE DESIGNATION = 'CLERK' AND SALARY > 3000;
-- Answer 3:
SELECT EMP_NAME FROM EMP WHERE LENGTH(EMP_NAME) = 5;
-- Answer 4:
SELECT * FROM EMP WHERE ROWNUM <= 5;
-- Answer 5:
SELECT * FROM EMP E1 WHERE SALARY > (SELECT AVG(SALARY) FROM EMP E2);
