-- =====================================
-- SECTION C: STUDENT, INSTRUCTOR
-- =====================================
CREATE TABLE STUDENT (
 STUD_ID NUMBER PRIMARY KEY,
 STUD_NAME VARCHAR2(50),
 COURSE VARCHAR2(50)
);
CREATE TABLE INSTRUCTOR (
 INSTRUCTOR_ID NUMBER PRIMARY KEY,
 NAME VARCHAR2(50),
 DEPARTMENT VARCHAR2(50),
 SALARY NUMBER
);
INSERT INTO STUDENT VALUES (1, 'Arun', 'Comp.Sci');
INSERT INTO STUDENT VALUES (2, 'Meena', 'Math');
INSERT INTO STUDENT VALUES (3, 'Ravi', 'Comp.Sci');
INSERT INTO STUDENT VALUES (4, 'Divya', 'Physics');
INSERT INTO STUDENT VALUES (5, 'Tom', 'Comp.Sci');
INSERT INTO INSTRUCTOR VALUES (1, 'Dr. Rao', 'Comp.Sci', 80000);
INSERT INTO INSTRUCTOR VALUES (2, 'Dr. Smith', 'Math', 70000);
INSERT INTO INSTRUCTOR VALUES (3, 'Dr. Lin', 'Physics', 72000);
INSERT INTO INSTRUCTOR VALUES (4, 'Dr. Raj', 'Chemistry', 65000);
INSERT INTO INSTRUCTOR VALUES (5, 'Dr. Zoe', 'Biology', 77000);
-- Answer 1:
SELECT DISTINCT STUD_NAME FROM STUDENT WHERE COURSE = 'Comp.Sci';
-- Answer 2:
-- Skipping course offerings logic due to lack of related table in original structure
-- Answer 3:
SELECT DEPARTMENT, MAX(SALARY) FROM INSTRUCTOR GROUP BY DEPARTMENT;
-- Answer 4:
SELECT MIN(MAX_SALARY) FROM (
 SELECT MAX(SALARY) AS MAX_SALARY FROM INSTRUCTOR GROUP BY DEPARTMENT
);
-- Answer 5:
SELECT STUD_NAME FROM STUDENT WHERE LOWER(STUD_NAME) LIKE 's%';
