-- =====================================
-- SECTION E: EMP, PROJECT
-- =====================================
CREATE TABLE EMP_E (
 E_ID NUMBER,
 E_NAME VARCHAR2(50),
 EMP_DEPT VARCHAR2(50),
 PROJECT_ID NUMBER
);
CREATE TABLE PROJECT (
 PROJECT_ID NUMBER,
 PROJECT_NAME VARCHAR2(100),
 PROJECT_START_DATE DATE,
 PROJECT_END_DATE DATE
);
INSERT INTO EMP_E VALUES (101, 'Aliya', 'HR', 1);
INSERT INTO EMP_E VALUES (102, 'Sam', 'Finance', 1);
INSERT INTO EMP_E VALUES (103, 'Ron', 'IT', 2);
INSERT INTO EMP_E VALUES (104, 'Sara', 'IT', 3);
INSERT INTO EMP_E VALUES (105, 'Vicky', 'Finance', 3);
INSERT INTO PROJECT VALUES (1, 'Alpha', TO_DATE('2022-01-01','YYYY-MM-DD'), TO_DATE('2022-
12-31','YYYY-MM-DD'));
INSERT INTO PROJECT VALUES (2, 'Beta', TO_DATE('2021-03-01','YYYY-MM-DD'), TO_DATE('2021-11-
20','YYYY-MM-DD'));
INSERT INTO PROJECT VALUES (3, 'Gamma', TO_DATE('2020-01-01','YYYY-MM-DD'), TO_DATE('2022-
05-10','YYYY-MM-DD'));
-- Answer 1:
SELECT PROJECT_ID, COUNT(DISTINCT EMP_DEPT) FROM EMP_E GROUP BY PROJECT_ID;
-- Answer 2:
SELECT COUNT(*) FROM PROJECT WHERE EXTRACT(YEAR FROM PROJECT_START_DATE) =
EXTRACT(YEAR FROM PROJECT_END_DATE);
-- Answer 3:
SELECT EMP_DEPT FROM EMP_E WHERE E_ID > 103;
-- Answer 4:
SELECT E_NAME FROM EMP_E WHERE LOWER(E_NAME) LIKE '%a';
