-- Create Tables
CREATE TABLE EMP_E (
    E_ID NUMBER,
    E_NAME VARCHAR2(50),
    EMP_DEPT VARCHAR2(50),
    PROJECT_ID NUMBER
);

CREATE TABLE PROJECT (
    PROJECT_ID NUMBER,
    PROJECT_NAME VARCHAR2(100),
    PROJECT_START_DATE DATE,
    PROJECT_END_DATE DATE
);

-- Insert Data into EMP_E
INSERT INTO EMP_E VALUES (101, 'Aliya', 'HR', 1);
INSERT INTO EMP_E VALUES (102, 'Sam', 'Finance', 1);
INSERT INTO EMP_E VALUES (103, 'Ron', 'IT', 2);
INSERT INTO EMP_E VALUES (104, 'Sara', 'IT', 3);
INSERT INTO EMP_E VALUES (105, 'Vicky', 'Finance', 3);

-- Insert Data into PROJECT
INSERT INTO PROJECT VALUES (1, 'Alpha', TO_DATE('2022-01-01','YYYY-MM-DD'), TO_DATE('2022-12-31','YYYY-MM-DD'));
INSERT INTO PROJECT VALUES (2, 'Beta', TO_DATE('2021-03-01','YYYY-MM-DD'), TO_DATE('2021-11-20','YYYY-MM-DD'));
INSERT INTO PROJECT VALUES (3, 'Gamma', TO_DATE('2020-01-01','YYYY-MM-DD'), TO_DATE('2022-05-10','YYYY-MM-DD'));

-- 1. List the number of departments of employees in each project.
SELECT PROJECT_ID, COUNT(DISTINCT EMP_DEPT) AS NUM_DEPARTMENTS
FROM EMP_E
GROUP BY PROJECT_ID;

-- 2. Same as above (duplicate question)
SELECT PROJECT_ID, COUNT(DISTINCT EMP_DEPT) AS NUM_DEPARTMENTS
FROM EMP_E
GROUP BY PROJECT_ID;

-- 3. How many projects started and finished in the same year.
SELECT COUNT(*) AS SAME_YEAR_PROJECTS
FROM PROJECT
WHERE EXTRACT(YEAR FROM PROJECT_START_DATE) = EXTRACT(YEAR FROM PROJECT_END_DATE);

-- 4. Select the department name of the company which is assigned to the employee whose employee id is greater than 103.
SELECT DISTINCT EMP_DEPT
FROM EMP_E
WHERE E_ID > 103;

-- 5. List name of all employees whose name ends with 'a'.
SELECT E_NAME
FROM EMP_E
WHERE E_NAME LIKE '%a';
