- =====================================
-- SECTION F: EMP, MANAGER
-- =====================================
CREATE TABLE EMP_F (
 EMPID NUMBER,
 EMP_NAME VARCHAR2(50),
 EMP_SALARY NUMBER,
 CITY VARCHAR2(50),
 PROJECT VARCHAR2(50)
);
CREATE TABLE MANAGER_F (
 MANAGER_ID NUMBER,
 EMP_NAME VARCHAR2(50),
 PROJECT VARCHAR2(50)
);
INSERT INTO EMP_F VALUES (1, 'Ankit', 12000, 'Toronto', 'P1');
INSERT INTO EMP_F VALUES (2, 'Nora', 14000, 'Toronto', 'P1');
INSERT INTO EMP_F VALUES (3, 'Harsh', 11000, 'Montreal', 'P2');
INSERT INTO MANAGER_F VALUES (986, 'Raj', 'P1');
INSERT INTO MANAGER_F VALUES (321, 'Asha', 'P2');
-- Answer 1:
SELECT EMPID, EMP_NAME FROM EMP_F WHERE PROJECT IN (SELECT PROJECT FROM MANAGER_F
WHERE MANAGER_ID = 986);
-- Answer 2:
SELECT COUNT(*) FROM EMP_F WHERE PROJECT = 'P1';
-- Answer 3:
SELECT EMPID FROM EMP_F WHERE EMP_SALARY BETWEEN 9000 AND 15000;
-- Answer 4:
SELECT EMP_NAME FROM EMP_F WHERE CITY = 'Toronto' AND PROJECT IN (SELECT PROJECT FROM
MANAGER_F WHERE MANAGER_ID = 321);
-- Answer 5:
SELECT MAX(EMP_SALARY), MIN(EMP_SALARY), AVG(EMP_SALARY) FROM EMP_F;
