-- =====================================
-- SECTION H: All Types of Join Operations
-- =====================================
-- Inner Join
SELECT * FROM EMP_B INNER JOIN COMPANY ON EMP_B.COMPANY_NAME =
COMPANY.COMPANY_NAME;
-- Left Outer Join
SELECT * FROM EMP_B LEFT OUTER JOIN COMPANY ON EMP_B.COMPANY_NAME =
COMPANY.COMPANY_NAME;
-- Right Outer Join
SELECT * FROM EMP_B RIGHT OUTER JOIN COMPANY ON EMP_B.COMPANY_NAME =
COMPANY.COMPANY_NAME;
-- Full Outer Join
SELECT * FROM EMP_B FULL OUTER JOIN COMPANY ON EMP_B.COMPANY_NAME =
COMPANY.COMPANY_NAME;
-- Cross Join
SELECT * FROM EMP_B CROSS JOIN COMPANY;
-- Self Join (Using alias to join EMP_B to itself on MANAGER_NAME)
SELECT E1.EMP_NAME AS EMPLOYEE, E2.EMP_NAME AS MANAGED_BY
FROM EMP_B E1, EMP_B E2
WHERE E1.MANAGER_NAME = E2.EMP_NAME;
